name: Build Stealerium

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          dotnet-version: 6.0

      - name: Install NuGet Packages
        run: nuget restore Stealerium.sln

      - name: Build solution
        run: msbuild -nologo -v:m -p:Configuration=${{ matrix.configuration }} Stealerium.sln

      - name: Move fimal build files one step back
        shell: cmd
        run: ren Binaries\Release\net6.0-windows .

      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - name: Build Artifact
        shell: powershell
        run: Compress-7Zip "Binaries\Release" -ArchiveFileName "Stealerium.zip" -Format Zip

      - name: Delete-tag-and-release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: AutoBuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: AutoBuild
          release_name: AutoBuild
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: tanyagray/action-upload-release-asset@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./Stealerium.zip
          asset_name: Stealerium.zip
          asset_content_type: application/zip
